Repository FACN4/Student-Project-TopCorner, pull requests merged in 2018-09, with the labels that each got.

#16 Database init
  package.json
  server/database/build.js
  server/database/build.sql
  server/database/dbconnection.js
  server/database/dummyData.json
  server/database/matches.json
  server/database/teams.json
  server/database/users.json
Labels: awaiting-review, solo

#17 Setup React & Express rel #6
  .gitignore
  client/package.json
  client/src/components/App.js
  client/src/components/customers.js
  package.json
  server/app.js
  server/server.js
Labels: merge-conflicts, solo

#18 Rexpress
  .gitignore
  client/package.json
  client/src/components/App.js
  client/src/components/customers.js
Labels: solo

#19 Database testing
  .gitignore
  package.json
  server/database/build.js
  server/database/build.sql
  server/database/dbconnection.js
  server/queries/getData.js
  testing/database_tests.js
Labels: in-review, solo

#24 Did more React setup >#6
  client/src/components/App.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/InputBox.js
  client/src/components/Predictions.js
  client/src/components/Row.js
  client/src/components/customers.js
  package.json
  server/database/users.json
  server/queries/getData.js
  server/server.js
  testing/database_tests.js
Labels: in-review, pair programmed

#28 Predictions page
  .DS_Store
  client/public/index.html
  client/src/assets/profilePhotos/Heyboy.jpeg
  client/src/assets/profilePhotos/Solgirl.jpg
  client/src/assets/profilePhotos/bennboy.jpeg
  client/src/assets/profilePhotos/mrrfvfd.jpeg
  client/src/components/App.js
  client/src/components/Predictions.js
  client/src/components/Row.js
  client/src/index.css
  server/database/matches.json
  server/database/users.json
  server/queries/getData.js
  server/server.js
Labels: awaiting-review, solo

#27 Router is set rel #25
  client/package.json
  client/src/components/App.js
Labels: awaiting-review, solo

#29 more predictions page. Loading screen. Images for buttons. Button Component > #10 #11
  client/src/assets/dir.php
  client/src/assets/images/createGroup.svg
  client/src/assets/images/dropDown.svg
  client/src/assets/images/edit.png
  client/src/assets/images/football.png
  client/src/assets/images/football.svg
  client/src/assets/images/register.png
  client/src/assets/images/save.svg
  client/src/assets/images/send.png
  client/src/assets/profilePhotos/bennyboy.jpeg
  client/src/components/App.js
  client/src/components/App/App.js
  client/src/components/App/App.style.js
  client/src/components/Button/Button.js
  client/src/components/Button/Button.style.js
  client/src/components/Footer.js
  client/src/components/Footer/Footer.js
  client/src/components/Footer/Footer.style.js
  client/src/components/Header.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.style.js
  client/src/components/InputBox/InputBox.js
  client/src/components/InputBox/InputBox.style.js
  client/src/components/Predictions/Predictions.js
  client/src/components/Predictions/Predictions.style.js
  client/src/index.js
  package.json
  server/database/matches.json
  server/database/users.json
Labels: in-review, solo

#30 Login signup page
  client/src/components/App/App.js
  client/src/components/Header/Header.js
  client/src/components/InputBox/InputBox.js
  client/src/components/InputBox/InputBox.style.js
  client/src/components/Table/Table.js
  client/src/components/Table/Table.style.js
  client/src/pages/HomePage/HomePage.js
  client/src/pages/HomePage/HomePage.style.js
  client/src/pages/LoginPage/LoginPage.js
  client/src/pages/LoginPage/LoginPage.style.js
  client/src/pages/NotFoundPage/NotFoundPage.js
  client/src/pages/NotFoundPage/NotFoundPage.style.js
  client/src/pages/PasswordRecoveryPage/PasswordRecoveryPage.js
  client/src/pages/PasswordRecoveryPage/PasswordRecoveryPage.style.js
  client/src/pages/PredictionsPage/PredictionsPage.js
  client/src/pages/PredictionsPage/PredictionsPage.style.js
  client/src/pages/ProfilePage/ProfilePage.js
  client/src/pages/ProfilePage/ProfilePage.style.js
  client/src/pages/SignupPage/SignupPage.js
  client/src/pages/SignupPage/SignupPage.style.js
Labels: hold, pair programmed

#38 Signup validation #22
  client/src/components/App/App.js
  client/src/components/Button/Button.js
  client/src/components/Header/Footer/Footer.js
  client/src/components/Header/Footer/Footer.style.js
  client/src/components/InputBox/InputBox.js
  client/src/pages/LoginPage/LoginPage.js
  client/src/pages/SignupPage/SignupPage.js
  client/src/pages/SignupPage/SignupPage.style.js
  server/controllers/error.js
  server/controllers/index.js
  server/controllers/login.js
  server/controllers/logout.js
  server/controllers/predictions.js
  server/registerHandler.js
  server/server.js
Labels: in-review, technical

#39 error handling for username or email exist > #22
  client/src/components/App/App.js
  client/src/pages/SignupPage/SignupPage.js
Labels: awaiting-review, solo

#42 login verification complete, but no cookies or redirect > #23
  client/src/components/App/App.js
  client/src/pages/LoginPage/LoginPage.js
  client/src/pages/LoginPage/LoginPage.style.js
  package.json
  server/handlers/loginHandler.js
  server/handlers/registerHandler.js
  server/queries/postData.js
  server/server.js
Labels: awaiting-review, solo

#45 Cookies. Login adds a cookie and logout removes a cookie.
  .gitignore
  client/src/components/App/App.js
  client/src/components/Header1/Header1.js
  client/src/helpers/validateCookie.js
  client/src/pages/LoginPage/LoginPage.js
  client/src/pages/LoginPage/LoginPage.style.js
  client/src/pages/PredictionsPage/PredictionsPage.js
  client/src/pages/SignupPage/SignupPage.style.js
  package.json
  server/handlers/cookieValidationHandler.js
  server/handlers/loginHandler.js
  server/server.js
Labels: awaiting-review, solo, technical

#50 Cookie validation > #46 #48
  client/src/App/App.js
  client/src/App/App.style.js
  client/src/assets/images/404.png
  client/src/components/App/App.js
  client/src/helpers/handleChange.js
  client/src/helpers/handleLogin.js
  client/src/helpers/handleLogout.js
  client/src/helpers/handleRegister.js
  client/src/helpers/validateCookie.js
  client/src/index.js
  client/src/pages/NotFoundPage/NotFoundPage.js
  client/src/pages/NotFoundPage/NotFoundPage.style.js
  client/src/pages/ProfilePage/ProfilePage.style.js
  server/handlers/cookieValidationHandler.js
  server/server.js
Labels: awaiting-review, solo, technical

#52 Various small issues > #49 #51
  client/src/App/App.js
  client/src/components/Button/Button.style.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.style.js
  client/src/components/Header1/Header1.js
  client/src/components/Header1/Header1.style.js
  client/src/components/Header2/Header2.js
  client/src/components/Header2/Header2.style.js
  client/src/components/InputBox/InputBox.js
  client/src/components/InputBox/InputBox.style.js
  client/src/components/Table/Table.js
  client/src/components/Table/Table.style.js
  client/src/components/WhiteBar/WhiteBar.js
  client/src/components/WhiteBar/WhiteBar.style.js
  client/src/helpers/handleChange.js
  client/src/helpers/handleLogin.js
  client/src/helpers/handleLogout.js
  client/src/helpers/handleRegister.js
  client/src/index.css
  client/src/pages/LoginPage/LoginPage.js
  client/src/pages/LoginPage/LoginPage.style.js
  client/src/pages/NotFoundPage/NotFoundPage.js
  client/src/pages/PredictionsPage/PredictionsPage.js
  server/handlers/registerHandler.js
Labels: awaiting-review, pair programmed
